server.port=8080

spring.application.name=gateway-service

spring.datasource.url=jdbc:h2:mem:gatewaydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

account-service.base-url=http://localhost:8081

resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=500ms
resilience4j.retry.instances.accountService.retry-exceptions[0]=java.io.IOException
resilience4j.retry.instances.accountService.retry-exceptions[1]=java.net.ConnectException
resilience4j.retry.instances.accountService.retry-exceptions[2]=com.eventledger.gateway.exception.ServiceUnavailableException

logging.level.root=INFO
logging.level.com.eventledger.gateway=INFO